version: "3.2"

networks:
  axiom:

services:

  axiom-web:
    build:
      context: .
    volumes:
      - ./docker/volumes/logs:/logs
    ports:
      - 4000:4000
    env_file:
      - .env
    networks:
      - axiom
